run:
  go: '1.21'
  timeout: 5m
  tests: false

issues:
  exclude-dirs:
    - utils
  exclude-rules:
    - path: /
      linters:
        - typecheck

output:
  formats:
    - format: colored-line-number
  sort-results: true

linters-settings:
  errcheck:
    check-blank: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - wsl

severity:
  default-severity: error
